import { describe, expect, it } from 'vitest'
import { allKana, hiragana, katakana } from '../data/kana'
import type { StudyPreferences, StudySession } from '../types/kana'
import { archiveSession, createActiveSession } from './session'
import { latestStudies, recentWrongCount, sessionSummary, slowReviewIds } from './stats'

const preferences: StudyPreferences = { characterSet:'hiragana', reviewMode:'none', slowReviewMode:'top-30', slowTopCount:30, slowThresholdMs:5000, reviewMistakesAtEnd:true, shuffled:false, lockNavigation:false, timerMs:null, recordSession:true, readyFirstCard:false, showKeyboardHints:true, reducedMotion:false }

describe('kana data',()=>{it('contains the basic 46 + 46 set with paired sounds',()=>{expect(hiragana).toHaveLength(46);expect(katakana).toHaveLength(46);expect(allKana).toHaveLength(92);expect(hiragana.map(k=>k.soundKey)).toEqual(katakana.map(k=>k.soundKey))})})
describe('sessions',()=>{it('archives deck order, primary scores and cumulative end-review timing',()=>{const active=createActiveSession(['hiragana-a'],preferences,'hiragana','study');active.deck[0]={...active.deck[0],graded:true,grade:'wrong',recognitionMs:500};active.reviewTimings['hiragana-a']=700;active.completed=true;const session=archiveSession(active);expect(session.deckOrder).toEqual(['hiragana-a']);expect(session.results[0]).toMatchObject({correctCount:0,wrongCount:1,recognitionTimes:[1200]});expect(sessionSummary(session).averageMs).toBe(1200)})
it('waits before starting the first card when ready mode is enabled',()=>{const active=createActiveSession(['hiragana-a'],{...preferences,timerMs:3000,readyFirstCard:true},'hiragana','study');expect(active.waitingToStart).toBe(true);expect(active.timerStartedAt).toBeNull()})
it('uses only the latest ten study sessions for mistakes',()=>{const sessions=Array.from({length:12},(_,i):StudySession=>({id:String(i),type:i===11?'review':'study',source:'hiragana',startedAt:i,finishedAt:i,shuffled:false,timerMs:null,reviewMistakesAtEnd:false,results:[{kanaId:'hiragana-a',correctCount:0,wrongCount:1,recognitionTimes:[]}]}));expect(latestStudies(sessions)).toHaveLength(10);expect(recentWrongCount(sessions,'hiragana-a')).toBe(10)})
it('builds slow review decks from average study timings across both alphabets',()=>{const sessions:StudySession[]=[{id:'study',type:'study',source:'both',startedAt:0,finishedAt:1,shuffled:false,timerMs:null,reviewMistakesAtEnd:false,results:[{kanaId:'hiragana-a',correctCount:1,wrongCount:0,recognitionTimes:[6000,4000]},{kanaId:'katakana-a',correctCount:1,wrongCount:0,recognitionTimes:[7000]}]},{id:'review',type:'review',source:'slowest',startedAt:2,finishedAt:3,shuffled:false,timerMs:null,reviewMistakesAtEnd:false,results:[{kanaId:'hiragana-i',correctCount:1,wrongCount:0,recognitionTimes:[9000]}]}];expect(slowReviewIds(sessions,'top-30',5000)).toEqual(['katakana-a','hiragana-a']);expect(slowReviewIds(sessions,'over-threshold',5000)).toEqual(['katakana-a'])})})
